[package]
name = "hula"
version = "2.6.6"
description = "hula"
authors = ["nongyehong"]
license = ""
repository = ""
edition = "2021"

[profile.release]
panic = "abort"   # 去掉昂贵的恐慌清理逻辑
codegen-units = 1 # 一个接一个地编译包，这样编译器就可以更好地优化
lto = true        # 启用链接到优化
opt-level = "s"   # 优化二进制文件大小,并且不会太大消耗性能,"z"极致优化大小但是会消耗性能
strip = true      # 删除调试符号

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hula_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.5", features = [
    "macos-private-api",
    "tray-icon",
    "image-png",
] }
tauri-plugin-os = "2.2.0"
tauri-plugin-shell = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = { version = "2.2.0", features = ["unsafe-headers"] }
tauri-plugin-process = "2.2.0"
tauri-plugin-fs = "2.0.1"
tauri-plugin-dialog = "2.2.0"
tauri-plugin-upload = "2.2.0"
tauri-plugin-global-shortcut = "2.2.0"
tauri-plugin-clipboard-manager = "2.2.0"
tauri-plugin-updater = "2.5.0"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-single-instance = "2.2.1"
tauri-plugin-notification = "2.2.1"
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-autostart = "2.2.0"
lazy_static = "1.4"
screenshots = "0.5.4"
base64 = "0.22.1"
rodio = "0.17.3"
reqwest = { version = "0.11", features = [
    "json",
    "socks",
    "native-tls-vendored",
] }


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is a URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
